### ISSUE TITLE
Issue creating conda environment for version1.5

### ISSUE THREAD

**Issue by andrewmaksymowsky** [kircherlab/CADD-scripts#13]
It looks like there's some version in incompatibilities in the 1.5 release yml. Wondering if there's a solution or work around ?

apple@hsc-buildbox CADD-scripts]$ conda env create -f src/environment_v1.5.yml
Collecting package metadata (repodata.json): done
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Package ncurses conflicts for:
pandas==0.20.3=py27_1 -> python=2.7 -> sqlite[version='>=3.20.1,<4.0a0'] -> ncurses==5.9
scikit-learn==0.20.1=py27h22eb022_0 -> python[version='>=2.7,<2.8.0a0'] -> ncurses[version='5.9.*|6.0.*|>=6.0,<7.0a0|>=6.1,<6.2.0a0|>=6.1,<7.0a0']                                                                                                                             
pysam==0.15.2=py27h0380709_0 -> python[version='>=2.7,<2.8.0a0'] -> ncurses[version='5.9.*|>=5.9,<5.10.0a0|>=6.0,<7.0a0|>=6.1,<6.2.0a0|>=6.1,<7.0a0']                                                                                                                          
pyvcf==0.6.8=py27_0 -> python[version='>=2.7,<2.8.0a0'] -> sqlite[version='>=3.20.1,<4.0a0'] -> ncurses==5.9
python==2.7.13=0 -> ncurses=5.9
pyvcf==0.6.8=py27_0 -> python[version='>=2.7,<2.8.0a0'] -> ncurses[version='5.9.*|6.0.*|>=6.0,<7.0a0|>=6.1,<6.2.0a0|>=6.1,<7.0a0']
scipy==1.0.1=py27_blas_openblas_200 -> python=2.7 -> sqlite[version='>=3.20.1,<4.0a0'] -> ncurses==5.9
numpy==1.14.2=py27_blas_openblas_200 -> python=2.7 -> sqlite[version='>=3.20.1,<4.0a0'] -> ncurses==5.9
numpy==1.14.2=py27_blas_openblas_200 -> python=2.7 -> ncurses[version='5.9.*|6.0.*|>=6.0,<7.0a0|>=6.1,<6.2.0a0|>=6.1,<7.0a0']
pysam==0.15.2=py27h0380709_0 -> python[version='>=2.7,<2.8.0a0'] -> sqlite[version='>=3.25.3,<4.0a0'] -> ncurses==5.9
scikit-learn==0.20.1=py27h22eb022_0 -> python[version='>=2.7,<2.8.0a0'] -> sqlite[version='>=3.20.1,<4.0a0'] -> ncurses==5.9
pandas==0.20.3=py27_1 -> python=2.7 -> ncurses[version='5.9.*|6.0.*|>=6.0,<7.0a0|>=6.1,<6.2.0a0|>=6.1,<7.0a0']
samtools==1.9=h91753b0_5 -> ncurses[version='>=6.1,<6.2.0a0']
scipy==1.0.1=py27_blas_openblas_200 -> python=2.7 -> ncurses[version='5.9.*|6.0.*|>=6.0,<7.0a0|>=6.1,<6.2.0a0|>=6.1,<7.0a0']
ensembl-vep==95.1=pl526ha4d7672_0 -> htslib -> curl[version='>=7.64.1,<8.0a0'] -> krb5[version='>=1.16.3,<1.17.0a0'] -> libedit[version='>=3.1.20170329,<3.2.0a0'] -> ncurses[version='5.9|5.9.*|6.0.*|>=6.0,<7.0a0|>=6.1,<6.2.0a0|>=6.1,<7.0a0']                              
samtools==1.9=h91753b0_5 -> curl[version='>=7.59.0,<8.0a0'] -> krb5[version='>=1.16.1,<1.17.0a0'] -> libedit[version='>=3.1.20170329,<3.2.0a0'] -> ncurses[version='>=6.1,<7.0a0']                                                                                             
Package libopenblas conflicts for:
pandas==0.20.3=py27_1 -> numpy[version='>=1.7'] -> openblas[version='>=0.3.3,<0.3.4.0a0'] -> libopenblas[version='0.3.3|0.3.6|0.3.6|0.3.6|0.3.6|0.3.6|0.3.6|0.3.6|0.3.7|0.3.7|0.3.7|0.3.7|>=0.3.6,<0.3.7.0a0|>=0.3.6,<1.0a0|>=0.3.7,<0.3.8.0a0|>=0.3.7,<1.0a0',build='h6e990d7_3|h6e990d7_1|h5a2b251_2|h5a2b251_1|h5a2b251_0|h5a2b251_1|h5a2b251_2|h5a2b251_3|h6e990d7_3|h6e990d7_4|h6e990d7_5|h6e990d7_6|h6e990d7_0|h6e990d7_2']                                                                                                                              
scipy==1.0.1=py27_blas_openblas_200 -> openblas[version='0.2.20|0.2.20.*'] -> libopenblas[version='>=0.2.20,<0.2.21.0a0|>=0.3.3,<1.0a0']                                                                                                                                       
pysam==0.15.2=py27h0380709_0 -> bcftools=1.9 -> gsl[version='>=2.5,<2.6.0a0'] -> libblas[version='>=3.8.0,<4.0a0'] -> libopenblas[version='>=0.3.6,<0.3.7.0a0|>=0.3.6,<1.0a0|>=0.3.7,<0.3.8.0a0|>=0.3.7,<1.0a0']                                                               
pysam==0.15.2=py27h0380709_0 -> bcftools=1.9 -> gsl[version='>=2.5,<2.6.0a0'] -> libblas[version='>=3.8.0,<4.0a0'] -> openblas[version='>=0.3.6,<0.3.7.0a0'] -> libopenblas[version='0.3.3|0.3.6|0.3.6|0.3.6|0.3.6|0.3.6|0.3.6|0.3.6|0.3.7|0.3.7|0.3.7|0.3.7|>=0.2.20,<0.2.21.0a0|>=0.3.2,<0.3.3.0a0',build='h6e990d7_3|h6e990d7_1|h5a2b251_2|h5a2b251_1|h5a2b251_0|h5a2b251_1|h5a2b251_2|h5a2b251_3|h6e990d7_3|h6e990d7_4|h6e990d7_5|h6e990d7_6|h6e990d7_0|h6e990d7_2']                                                                                       
numpy==1.14.2=py27_blas_openblas_200 -> openblas[version='0.2.20|0.2.20.*'] -> libopenblas[version='>=0.2.20,<0.2.21.0a0']
pandas==0.20.3=py27_1 -> numpy[version='>=1.7'] -> libopenblas[version='>=0.2.20,<0.2.21.0a0|>=0.3.2,<0.3.3.0a0|>=0.3.3,<1.0a0']
scikit-learn==0.20.1=py27h22eb022_0 -> libopenblas[version='>=0.3.3,<1.0a0']
scipy==1.0.1=py27_blas_openblas_200 -> numpy[version='>=1.9'] -> libblas[version='>=3.8.0,<4.0a0'] -> libopenblas[version='>=0.3.2,<0.3.3.0a0|>=0.3.6,<0.3.7.0a0|>=0.3.6,<1.0a0|>=0.3.7,<0.3.8.0a0|>=0.3.7,<1.0a0']                                                            
scikit-learn==0.20.1=py27h22eb022_0 -> blas=[build=openblas] -> openblas -> libopenblas[version='0.3.3|0.3.6|0.3.6|0.3.6|0.3.6|0.3.6|0.3.6|0.3.6|0.3.7|0.3.7|0.3.7|0.3.7|>=0.2.20,<0.2.21.0a0|>=0.3.2,<0.3.3.0a0|>=0.3.6,<0.3.7.0a0|>=0.3.6,<1.0a0|>=0.3.7,<0.3.8.0a0|>=0.3.7,<1.0a0',build='h6e990d7_3|h6e990d7_1|h5a2b251_2|h5a2b251_1|h5a2b251_0|h5a2b251_1|h5a2b251_2|h5a2b251_3|h6e990d7_3|h6e990d7_4|h6e990d7_5|h6e990d7_6|h6e990d7_0|h6e990d7_2']                                                                                                       
Package tk conflicts for:
ensembl-vep==95.1=pl526ha4d7672_0 -> perl-bioperl[version='>=1.7.2'] -> perl-bio-tools-run-alignment-tcoffee -> t_coffee -> python=3.4 -> tk=8.5                                                                                                                               
numpy==1.14.2=py27_blas_openblas_200 -> python=2.7 -> tk[version='8.5.*|8.6.*|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
pandas==0.20.3=py27_1 -> python=2.7 -> tk[version='8.5.*|8.6.*|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
samtools==1.9=h91753b0_5 -> curl[version='>=7.59.0,<8.0a0'] -> krb5[version='>=1.16.1,<1.17.0a0'] -> tk[version='8.6.*|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']                                                                                                    
ensembl-vep==95.1=pl526ha4d7672_0 -> htslib -> curl[version='>=7.64.1,<8.0a0'] -> krb5[version='>=1.16.3,<1.17.0a0'] -> tk[version='8.6.*|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']                                                                                 
pyvcf==0.6.8=py27_0 -> python[version='>=2.7,<2.8.0a0'] -> tk[version='8.5.*|8.6.*|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
python==2.7.13=0 -> tk=8.5
pysam==0.15.2=py27h0380709_0 -> python[version='>=2.7,<2.8.0a0'] -> tk[version='8.5.*|8.6.*|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']                                                                                                                               
scikit-learn==0.20.1=py27h22eb022_0 -> python[version='>=2.7,<2.8.0a0'] -> tk[version='8.5.*|8.6.*|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']                                                                                                                        
scipy==1.0.1=py27_blas_openblas_200 -> python=2.7 -> tk[version='8.5.*|8.6.*|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']

**Comment by aerval** [comment]
Unfortunately, the only solution to this is to include the whole list of installed packages from an installed environment. Hope this fixes the issue, though maintaining this is not pretty.

**Comment by andrewmaksymowsky** [comment]
Thanks for the fix ! It resolved my problem with the version conflicts.
