### ISSUE TITLE
Error running CADD

### ISSUE THREAD

**Issue by nuin** [kircherlab/CADD-scripts#15]
Hi

I did an install with the install script, with a Conda environment, everything seemed fine until I tried running the first test and I got this error (added some lines

```bash
(cadd-env) ➜  CADD-scripts git:(master) ./CADD.sh test/input.vcf
CADD-v1.5 (c) University of Washington, Hudson-Alpha Institute for Biotechnology and Berlin Institute of Health 2013-2019. All rights reserved.
/home/nuin/anaconda3/etc/profile.d/conda.sh: line 29: PS1: unbound variable
(cadd-env) ➜  CADD-scripts git:(master) nano /home/nuin/anaconda3/etc/profile.d/conda.sh
(cadd-env) ➜  CADD-scripts git:(master) echo $PS1
(cadd-env) %(?:%{%}➜ :%{%}➜ ) %{$fg[cyan]%}%c%{$reset_color%} $(git_prompt_info)
```

Same result with ZSH and BASH.

Any help appreciated

Thanks

**Comment by aerval** [comment]
Hi,

Thanks for reporting this issue. Google tells me that this seems to be an [old bug in virtualenv](https://github.com/pypa/virtualenv/pull/922) (the program that creates/activates the CADD conda environment) that has been fixed a while ago. So I assume, the most simple way to fix this would be for you to update virtualenv (i.e `pip install --upgrade virtualenv`). If that is not possible for you [as a workaround set by defining the](https://stackoverflow.com/questions/42997258/virtualenv-activate-script-wont-run-in-bash-script-with-set-euo) `PS1` variable in the CADD script via adding a line like `PS1=${PS1:-}` at the beginning of the CADD script.

Cheers, Philipp

**Comment by nuin** [comment]
Hi

exporting `PS1=${PS1:-}` did the trick for the original error, but now I get stuck in another error, that I will open a new ticket.

Thanks
