### ISSUE TITLE
Installation of CADD1.6 (01/07/2020)

### ISSUE THREAD

**Issue by MikeHala** [kircherlab/CADD-scripts#19]
Dear CADD Team,
Thank you for providing this useful resource. I have been using CADD1.3 for some time, but had to update to 1.6. 
Here are my installation notes with the hope they may help someone; please feel free to edit as you see fit.

- use **miniconda3**, otherwise cannot install snakemake 
UnsatisfiableError: 
The following specifications were found to be incompatible with the existing python installation in your environment:
snakemake -> python[version='3.4.*|3.5.*|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|3.6.*']
Your python: python=2.7
- unset PYTHONPATH, otherwise a warning about potential python conflicts
- edit install.sh, replace --create-envs-only with --conda-create-envs-only 
otherwise: snakemake: error: unrecognized arguments: --create-envs-only

**wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
unset PYTHONPATH
bash Miniconda3-latest-Linux-x86_64.sh -p $HOME/miniconda3 -b
export PATH=$HOME/miniconda3/bin:$PATH
conda install -c conda-forge -c bioconda snakemake**

go to https://github.com/kircherlab/CADD-scripts/ , "Clone", “Download ZIP”, copy to destination, unzip
**edit install.sh**, replace --create-envs-only with --conda-create-envs-only

* downloading only GRCh38 SNP datasets (takes some time, make sure you have enough space)
**./install.sh**
Do you want to install the virtual environments with all CADD dependencies via conda? (y)/n y
Do you want to install CADD v1.6 for GRCh37/hg19? (y)/n n
Do you want to install CADD v1.6 for GRCh38/hg38? (y)/n y
Do you want to load annotations (Annotations can also be downloaded manually from the website)? (y)/n y
Do you want to load prescored variants (Makes SNV calling faster. Can also be loaded/installed later.)? y/(n) y
Do you want to load prescored variants for scoring with annotations (Warning: These files are very big)? y/(n) n
Do you want to load prescored variants for scoring without annotations? y/(n) y
Do you also want to load prescored InDels? We provide scores for well known InDels from sources like ClinVar, gnomAD/TOPMed etc. y/(n) n

* run a test
**./CADD.sh test/input.vcf**

I am not sure if I have to load annotations (the 4th entry above) if I only want to produce a file with the CADD scores for a list of SNPs (no annotations). Can you please comment?

**Comment by aerval** [comment]
Dear @MikeHala,

Thank you for your interest in the new CADD version and your helpful documentation.

While in principle it would be possible without annotations to only retrieve SNVs from the prescored files, the scripts have not been adapted as such. It is therefore necessary right now to download the annotations, even if it does not do much in your case. However, it would be possible to adapt the script quite easily to such a mode by changing in `rule prescore` in the file  `Snakefile` in
line 28 from `prescored=temp('{file}.pre.tsv')` to `prescored=temp('{file}.tsv.gz')`
add line after line 48: `gzip {output.prescored}; mv {output.prescored}.gz {output.prescored}`
and remove everything beyond line 50.

Note however, that this will discard any variants that are not in the prescored files without warning (if you are only scoring SNV that should not be a big problem though).

Regards, Philipp
