### ISSUE TITLE
CADD 1.6 in VEP

### ISSUE THREAD

**Issue by danchubb** [kircherlab/CADD-scripts#20]
Hi,

This isn't quite an issue, but I am having trouble working this out from the VEP help pages and I hope you can help. Do you know if vep (I'm using v100) is able to annotate the new 1.6 CADD scores? I'm assuming if I download the pre-scored files it should work ok? Do you know if it is able to score novel indels or will it just take the pre-scored files and look up the relevant affects? Or would I need to download and run the CADD code if I wanted a CADD score for novel indels?

Thanks a lot

Dan

**Comment by makirc** [comment]
Hi Dan, 

Thank you for your interest in CADD and message. You are right though, this really does not belong here. If you have these kinds of general support requests please contact us through the support email address (https://cadd.gs.washington.edu/contact). 

From what I understand, VEP generally supports allele-specific (which you need for CADD) custom annotations in VCF format (https://www.ensembl.org/info/docs/tools/vep/script/vep_custom.html). So if you want to go this path, you would need to slightly reformat the pre-scored files. It would not allow you to score new InDels. If you want to retrieve scores for new indels, you need to go through the CADD script release or our webserver.

In addition to the custom annotation support, VEP comes with a direct support for CADD. In it's current version this is CADD 1.5. With the VEP script install you should be able to replace the CADD 1.5 path with the 1.6 files that you download from us (incl. tbi files that you put in the same location). The VEP command line would look something like that:

 ./vep --plugin CADD,[path_to]/CADD_GRCh38_1.6_whole_genome_SNVs.tsv.gz,[path_to]/CADD_GRCh38_1.6_InDels.tsv.gz --species homo_sapiens --cache --input_file [input_data] --output_file [output_file]

Replacing the files should work as it is the exact same format in v1.5 and v1.6. Again, it would not allow you to score new InDels, you the CADD script release or our webserver for that.

Should you have further questions, please contact us by email. I will close this issue now.

Best,

Martin
