### ISSUE TITLE
Location of annotation for downloading needs update

### ISSUE THREAD

**Issue by jjfarrell** [kircherlab/CADD-scripts#21]
The Readme file needs an update for the location of the annotation files...

This line need to be changed from:
```
wget -c http://krishna.gs.washington.edu/download/CADD/v1.6/annotationsGRCh38_v1.6.tar.gz
to:
```
`wget -c https://krishna.gs.washington.edu/download/CADD/v1.6/GRCh38/annotationsGRCh38_v1.6.tar.gz
`

Similar for 37.

**Comment by aerval** [comment]
Thank you very much for letting us know of this issue!
