### ISSUE TITLE
Missing Packages when running on test.vcf

### ISSUE THREAD

**Issue by williamphu** [kircherlab/CADD-scripts#22]
Hi there, I'm attempting to run CADD on a VM, and I've ran the install.sh script. When I try to run CADD on the test provided, it gives me this error read out:

`Running snakemake pipeline:
snakemake /tmp/tmp.fGiFALQq9Y/input.tsv.gz --use-conda --conda-prefix /home/wphu/CADD-scripts-master/envs --cores 1
--configfile /home/wphu/CADD-scripts-master/config/config_GRCh38_v1.6_noanno.yml --snakefile /home/wphu/CADD-script
s-master/Snakefile -q
Job counts:
        count   jobs
        1       annotation
        1       imputation
        1       join
        1       prepare
        1       prescore
        1       score
        6
/bin/bash: activate: No such file or directory
/bin/bash: activate: No such file or directory
Opening /home/wphu/CADD-scripts-master/data/prescored/GRCh38_v1.6/no_anno/gnomad.genomes.r3.0.indel.tsv.gz...
Opening /home/wphu/CADD-scripts-master/data/prescored/GRCh38_v1.6/no_anno/whole_genome_SNVs.tsv.gz...
/bin/bash: activate: No such file or directory
/bin/bash: line 1: vep: command not found
Traceback (most recent call last):
  File "/home/wphu/CADD-scripts-master/src/scripts/annotateVEPvcf.py", line 3, in <module>
    from ConfigParser import ConfigParser
ModuleNotFoundError: No module named 'ConfigParser'
[Wed Oct  7 23:34:47 2020]
Error in rule annotation:
    jobid: 4
    output: /tmp/tmp.fGiFALQq9Y/input.anno.tsv.gz
    conda-env: /home/wphu/CADD-scripts-master/envs/457093c1
RuleException:
CalledProcessError in line 55 of /home/wphu/CADD-scripts-master/Snakefile:
Command 'source activate /home/wphu/CADD-scripts-master/envs/457093c1; set -euo pipefail;  
        cat /tmp/tmp.fGiFALQq9Y/input.novel.vcf         | vep --quiet --cache --offline --dir $CADD/data/annotation
s/GRCh38_v1.6/vep             --buffer 1000 --no_stats --species homo_sapiens             --db_version=95 --assembl
y GRCh38             --format vcf --regulatory --sift b --polyphen b --per_gene --ccds --domains             --numb
ers --canonical --total_length --vcf --force_overwrite --output_file STDOUT         | python $CADD/src/scripts/anno
tateVEPvcf.py             -c $CADD/config/references_GRCh38_v1.6.cfg         | gzip -c > /tmp/tmp.fGiFALQq9Y/input.
anno.tsv.gz ' returned non-zero exit status 1.
  File "/home/wphu/CADD-scripts-master/Snakefile", line 55, in __rule_annotation
  File "/home/wphu/miniconda3/envs/cadd/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Exiting because a job execution failed. Look above for error message`

The top issue seems to be that I'm missing some packages. I've tried installing them with pip, but I think that the conda environment CADD is running in is distinct from the environment the machine is sitting in. I've tried deleting and reinstalling the CADD folder multiple times, with the same result.

Could you help with what is probably environment issues?

**Comment by aerval** [comment]
Dear @williamphu,

Thank you for your question. To be honest I am not entirely sure what is going on here but this does not look like something is missing from your conda installation. Can you specify which version of conda and snakemake you are using? Further, it seems that your installation of conda does miss the activate function (similar to this issue: https://github.com/ContinuumIO/anaconda-issues/issues/9539), can you check if your `$conda/bin` directory contains `activate`? Please also check if `conda env list` returns the CADD environment under `/home/wphu/CADD-scripts-master/envs/3415713f`. If that is the case, you should be able to activate it via `conda activate /home/wphu/CADD-scripts-master/envs/3415713f`.

Maybe this gets us in the right direction,

**Comment by williamphu** [comment]
Hi @aerval,

Thanks for your help. My conda version is 4.8.3, and my snakemake version is 5.3.0. I am able to activate both the CADD environment, as well as use the activate function as described in the above link. One thing I did do is re-export the miniconda path, which seems to have resolved the missing activate functions. Unfortunately it seems I'm still missing "ConfigParser":

`Running snakemake pipeline:
snakemake /tmp/tmp.ZkQSXGJ1UQ/input.tsv.gz --use-conda --conda-prefix /home/wphu/CADD-scripts-master/envs --cores 1
--configfile /home/wphu/CADD-scripts-master/config/config_GRCh38_v1.6_noanno.yml --snakefile /home/wphu/CADD-scripts-master/Snake
file -q
Job counts:
        count   jobs
        1       annotation
        1       imputation
        1       join
        1       prepare
        1       prescore
        1       score
        6
Opening /home/wphu/CADD-scripts-master/data/prescored/GRCh38_v1.6/no_anno/gnomad.genomes.r3.0.indel.tsv.gz...
Opening /home/wphu/CADD-scripts-master/data/prescored/GRCh38_v1.6/no_anno/whole_genome_SNVs.tsv.gz...
Traceback (most recent call last):
  File "/home/wphu/CADD-scripts-master/src/scripts/annotateVEPvcf.py", line 3, in <module>
    from ConfigParser import ConfigParser
ModuleNotFoundError: No module named 'ConfigParser'
Possible precedence issue with control flow operator at /home/wphu/CADD-scripts-master/envs/457093c1/lib/site_perl/5.26.2/Bio/DB/
IndexedBase.pm line 805.
[Tue Oct 13 14:48:55 2020]
Error in rule annotation:
    jobid: 4
    output: /tmp/tmp.ZkQSXGJ1UQ/input.anno.tsv.gz
    conda-env: /home/wphu/CADD-scripts-master/envs/457093c1
RuleException:
CalledProcessError in line 55 of /home/wphu/CADD-scripts-master/Snakefile:
Command 'source activate /home/wphu/CADD-scripts-master/envs/457093c1; set -euo pipefail;  
        cat /tmp/tmp.ZkQSXGJ1UQ/input.novel.vcf         | vep --quiet --cache --offline --dir $CADD/data/annotations/GRCh38_v1.6/
vep             --buffer 1000 --no_stats --species homo_sapiens             --db_version=95 --assembly GRCh38             --forma
t vcf --regulatory --sift b --polyphen b --per_gene --ccds --domains             --numbers --canonical --total_length --vcf --for
ce_overwrite --output_file STDOUT         | python $CADD/src/scripts/annotateVEPvcf.py             -c $CADD/config/references_GRC
h38_v1.6.cfg         | gzip -c > /tmp/tmp.ZkQSXGJ1UQ/input.anno.tsv.gz ' returned non-zero exit status 1.
  File "/home/wphu/CADD-scripts-master/Snakefile", line 55, in __rule_annotation
  File "/home/wphu/miniconda3/envs/cadd/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Exiting because a job execution failed. Look above for error message`

To clarify, does the conda environment under the CADD-scripts-master need to be the active conda env when running CADD?

**Comment by williamphu** [comment]
Hi @aerval,

I wanted to give an update. After tracking down the line `Traceback (most recent call last): File "/home/wphu/CADD-scripts-master/src/scripts/annotateVEPvcf.py", line 3, in <module> from ConfigParser import ConfigParser ModuleNotFoundError: No module named 'ConfigParser'`, I edited the `annotateVEPvcf.py` file, which originally had the line `from ConfigParser import ConfigParser` to `from configparser import ConfigParser`, which resolved the issue importing `ConfigParser`. That then lead me to an issue that `pysam` was not installed. I double checked my environments, install pysam both in the CADD created conda env, as well as the env I was running `CADD.sh` from. After re-exporting my python path, and deactivating all conda envs and then reactivating the envs, I was able to successfully run the test input, and got the correct result.

I think that the `ConfigParser` issue might be genuine, while the later issues might have been my environments getting mixed up. What do you think?

**Comment by makirc** [comment]
Dear William, 
To me, this sounds like a wrong version of Python. CADD is running on Python 2.7. Based on your naming, it suggests that you are on Python 3.x. Pysam should be is installed in the CADD environment, but it sounds like you are not getting the right version of python/activation of the right environment.  
Hope that helps,
Martin

**Comment by williamphu** [comment]
Yes, I probably am running into an issue with the python version. I reverted back to 3.x because it appeared that Snakemake could not be installed with 2.7, an issue brought up in #19 , but I'll keep working on it.

**Comment by aerval** [comment]
No, do not revert to an earlier version. We are also running CADD via Python 3, that is not an issue. The CADD conda environment installs its own python2.7. However, it may be that when you activate the CADD environment, python3 still takes precendence over python2. Can you activate the environment again in your command line and check with `which python` which python instance is called. Anyways, changing in line 62 of `Snakefile` the word `python` to `python2` might cause the right python version to be called. However,  there still must be a reason why python3 is called in your workflow as the environment as such should (install and) provide the right python version on its own.

**Comment by williamphu** [comment]
Hi everyone, thanks for your help. Seeing as how it still looked like an environment issue, I installed CADD on a fresh VM which worked without any issues. I must have crossed my environments at some point.
