### ISSUE TITLE
Empty analysis - Temp CSV file is empty - "Encountered uncovered chromosome"

### ISSUE THREAD

**Issue by williamphu** [kircherlab/CADD-scripts#23]
I'm trying to run CADD on my own vcf file, and it is giving me "Encountered uncovered chromosome" messages and the resulting analysis is empty. In addition, one of the temporary files generated is empty - `"Input file /tmp/tmp.pdJOZKL5qm/CADD_split_vsmall.csv.gz is empty."` When I submit this file to the CADD server for analysis, it does return a score and result. Is there any advice for input files when I run it myself? Thanks.

**Comment by makirc** [comment]
Hi William, 
glad to see that your other issue was solved. This one might be easy. The webserver trims off "chr" in the beginning of a chromosome ID, the offline installation does not do it. In case you are using UCSC chromosome names, this will cause problems. Please strip away your chr and only use the 22 autosomes plus X and Y. 
Best,
Martin

**Comment by williamphu** [comment]
Thanks! That was the issue.
