### ISSUE TITLE
MissingInputException

### ISSUE THREAD

**Issue by jianhuig** [kircherlab/CADD-scripts#28]
Hi,

Previously I had no problem of running CADD. However, after recent re-installation, I got the following error

```console
CADD-scripts-master$ snakemake test/input.vcf --use-conda --conda-create-envs-only --conda-prefix ./envs -j1 --configfile config/config_GRCh38_v1.6.yml --snakefile Snakefile

Building DAG of jobs...
MissingInputException in line 4 of ~/CADD-scripts-master/Snakefile:
Missing input files for rule decompress:
test/input.vcf.gz
```
I did not quite understand this issue, because my input file does not have .gz extension.
Any help is appreciated

conda 4.9.2
snakemake 6.0.0

**Comment by aerval** [comment]
Hi,

To run snakemake and setup the conda environment, the command should not provide the input file as in your case, but the output file.
Accordingly, the correct command is:
```
snakemake test/input.tsv.gz --use-conda --conda-create-envs-only --conda-prefix ./envs -j1 --configfile config/config_GRCh38_v1.6.yml --snakefile Snakefile
```
as it is used in the install.sh script. WIth your command, snakemake tries to generate `test/input.vcf` for which it has no input file.
I hope this fixes your problems.

Cheers, Philipp

**Comment by jianhuig** [comment]
Thanks for your fast reply! It indeed solved my problem. It might be helpful for other users as well if you change this in read.me

As of this version, dependencies have to be installed via conda and snakemake. This is because we are using two different enviroments for python2 and python3.

snakemake test/input.vcf --use-conda --conda-create-envs-only --conda-prefix envs \
        --configfile config/config_GRCh38_v1.6.yml --snakefile Snakefile

Thanks again

**Comment by aerval** [comment]
I see, I had missed the readme, thanks for pointing that out.
