### ISSUE TITLE
Expansion of annotations in CADD v1.6

### ISSUE THREAD

**Issue by SBNoor** [kircherlab/CADD-scripts#31]
Hi, I was going through release notes of CADD v1.6. In this version, 134 annotations are used. And n-level categorical values, such as reference allele identity, are converted to n individual Boolean flags. When I expand these annotations I end up getting 214 features for each variant. Whereas, in the original article 949 features are mentioned. Can you briefly explain how do you expand these annotations to get 949 features?
Thank you!

**Comment by makirc** [comment]
Please see the section "Summary of CADD v1.6 models" in https://genomemedicine.biomedcentral.com/articles/10.1186/s13073-021-00835-9
