### ISSUE TITLE
one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!

### ISSUE THREAD

**Issue by caeareva** [kircherlab/CADD-scripts#32]
I am running CADD in a virtual environment. I believe I have installed all dependencies, however, I keep getting this error and wonder if someone could provide insights in how to solve it? This occurs when running the sample file, command:

> ./CADD.sh -a -g GRCh37 -o output_inclAnno_GRCh37.tsv.gz -----/driverpowerEnv/CADD-scripts-master/test/input.vcf 

Output: 

> Job counts:
> 	count	jobs
> 	1	annotation
> 	1	imputation
> 	1	join
> 	1	prepare
> 	1	prescore
> 	1	score
> 	6
> [Sun Apr 11 11:53:33 2021]
> Error in rule prepare:
>     jobid: 2
>     output: /scratch/tmp/tmp.ksJO4PiOzk/input.prepared.vcf
>     conda-env: -------/driverpowerEnv/CADD-scripts-master/envs/99ccf3ab2dba635be40bcab17c5b364d
>     shell:
>         
>         cat /scratch/tmp/tmp.ksJO4PiOzk/input.vcf         | python $CADD/src/scripts/VCF2vepVCF.py         | sort -k1,1 -k2,2n -k4,4 -k5,5         | uniq > /scratch/tmp/tmp.ksJO4PiOzk/input.prepared.vcf
>         
>         (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
> 
> Exiting because a job execution failed. Look above for error message

Thank you so much!

**Comment by aerval** [comment]
Hi,
That is unfortunately a very general error message.
Can you post a vcf file that you are using that is producing the error?
Also may be you can activate the CADD environment from conda, i.e `conda activate /private/groups/brookslab/carevalo/driverpowerEnv/CADD-scripts-master/envs/99ccf3ab2dba635be40bcab17c5b364d` and then execute the failing step in your shell, i.e `cat -----/driverpowerEnv/CADD-scripts-master/test/input.vcf | python $CADD/src/scripts/VCF2vepVCF.py | sort -k1,1 -k2,2n -k4,4 -k5,5         | uniq > input.prepared.vcf` and report any errors and the output file.

**Comment by caeareva** [comment]
Yes, I am using the sample input file from the CADD Github repository:  /test/input.vcf
When I try to activate the conda environment, using conda activate  ..../CADD-scripts-master/envs/99ccf3ab2dba635be40bcab17c5b364d, I get the following error:

Not a conda environment: ..../CADD-scripts-master/envs/99ccf3ab2dba635be40bcab17c5b364d

I installed CADD following the tutorial in Github, so I am not sure why I can't activate it.


Thank you so much!

**Comment by aerval** [comment]
Sorry, for the slow reply, but I have no idea what your problem is, seems to be a general conda issue that has not much to do with the CADD pipeline. Have you been using conda before? Which version of snakemake and conda are you using? Also, which tutorial did you use? The installation script or the one from the readme?
