### ISSUE TITLE
Feature request: In-memory annotation with python

### ISSUE THREAD

**Issue by Hoeze** [kircherlab/CADD-scripts#33]
Hi, would it be possible to use CADD-scripts as a python library to annotate dataframes of variants, without writing files to disk?
For example, something like this:
```python
>>> variants_df.columns
["chrom", "pos", "ref", "alt", "vep_consequences"]

>>> import cadd_scripts
>>> cadd_scripts.annotate(variants_df)
["chrom", "pos", "ref", "alt", "vep_consequences", "other", "annotations", ...]
```

**Comment by makirc** [comment]
It would require to wrap Ensembl Variant Effect predictor into a python library. This seems some effort and woulld probably still require temporary files or pipes. What do you need it for? Do you need to score indels/multi-allelic substitutions from scratch or are you anyways just looking up pre-scored SNVs? If it is pre-scored SNVs, it can all be done with the pysam/tabix library or with API calls (https://cadd.gs.washington.edu/api).

**Comment by Hoeze** [comment]
I'd like to annotate a large number of rare variants on the fly in parallel.
Having to store the variants in a file, pass them to CADD and read the results again makes this hard to implement.

What information from VEP do you need?
We can already query variant consequences on the fly, so this would not be a large issue for me.

**Comment by makirc** [comment]
Sorry for that, but getting variants annotated is one of the harder parts in CADD. As mentioned before, if it is SNVs, use the pre-scored files. Scoring large numbers of variants from scratch is time intense.

We are getting a good number of annotations columns from VEP [https://cadd.gs.washington.edu/static/ReleaseNotes_CADD_v1.6.pdf]: 
(AnnoType)
Consequence
(ConsScore)
(ConsDetail)
GC
CpG
motifECount
(motifEName)
motifEHIPos
motifEScoreChng
oAA
nAA
(GeneID)
(FeatureID)
(GeneName)
(CCDS)
(Intron)
(Exon)
cDNApos
Dst2Splice
Dst2SplType
SIFTcat
SIFTval
PolyPhenCat
PolyPhenVal
