### ISSUE TITLE
empty imputation file when looking into SNVs alone

### ISSUE THREAD

**Issue by SBNoor** [kircherlab/CADD-scripts#35]
I have a vcf files of just SNVs. When I run CADD pipeline it produces an empty imputation file. But when I include deletions and insertions in my vcf file, it produces an imputation file with deletions + insertions but not SNVs. Why is that? Could you provide some insights on this.

**Comment by makirc** [comment]
I assume because you are using a pre-scored SNV file. In this case, there is no intermediate imputation file, as SNVs would be directly retrieved from the pre-scored file.

**Comment by SBNoor** [comment]
Is there a way to obtain imputation for SNVs too? So by-pass pre-scored SNV file in a way?

**Comment by makirc** [comment]
Putting no files in data/prescored/${GENOME_BUILD}_${VERSION}/. For example, simple rename the prescored folder.
