### ISSUE TITLE
Only a small percentage of SNVs receiving annotation using offline tool

### ISSUE THREAD

**Issue by realviacauchy** [kircherlab/CADD-scripts#36]
Hello,
I have attached markdown output where I have done my best to illustrate and debug the issue I am having where the annotated output file only contains annotation for a small number of SNVs and the rest only these columns: Chr, Pos, A1, A2, RawScore, PHRED.
[CADD_debug_08042021.pdf](https://github.com/kircherlab/CADD-scripts/files/6933582/CADD_debug_08042021.pdf)

**Comment by makirc** [comment]
Hi there, 
as you suspect in your detailed report, having a file without annotations in your "incl_anno" folder is the problem. Please move /scratch/groups/abattle4/jessica/RareVar_AFR/cadd/CADD-scripts/data/prescored/GRCh38_v1.6/incl_anno/gnomad.genomes.r3.0.snv.tsv.gz to another folder and please try again. 
Best,
Martin
