### ISSUE TITLE
CADD 1.6: Encountered uncovered chromosome/Possible precedence issue with control flow operator

### ISSUE THREAD

**Issue by zyh4482** [kircherlab/CADD-scripts#37]
I've installed gnomad.genomes.r3.0.indel_inclAnno.tsv.gz and whole_genome_SNVs_inclAnno.tsv.gz under prescored/GRCh38_v1.6/incl_anno. 

command line:
`./CADD.sh -a -g GRCh38 -o ~/data/output.txt ~/data/input.vcf`

It reports with following message:

```
Encountered uncovered chromosome
Encountered uncovered chromosome
Encountered uncovered chromosome
Encountered uncovered chromosome
Possible precedence issue with control flow operator at /home/tomas/CADD/CADD-scripts-master/envs/bbfedf5e67480733367291efe3002c46/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 805.
```

What happened here? 

btw. I notice test.vcf does not have any headers and columns after ALT. Is it necessary to reformat my vcf?

**Comment by zyh4482** [comment]
I just found my issue is replicated. 

https://github.com/kircherlab/CADD-scripts/issues/23

After removing chr using following command:
`awk '{gsub(/^chr/,""); print}' your.vcf > no_chr.vcf`

It works normally. I'll close this issue.

**Comment by zyh4482** [comment]
I could fix `encounterred uncovered chromosome` issue. 
But the other message `Possible precedence issue with control flow operator at /home/tomas/CADD/CADD-scripts-master/envs/bbfedf5e67480733367291efe3002c46/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 805.` still comes out. 

Does it have any impact on result?

**Comment by makirc** [comment]
Hi there! Yes, the "encountered uncovered chromosome" just means that you defined chromosome names in your input file that are not found in the respective reference sequence. As you noticed, this might be an additional "chr" string that is not present in the reference sequence that CADD is using. The second message is a perl warning. We receive it on some systems too, it does not seem to be critical and can be ignored. Best, Martin
