### ISSUE TITLE
How to get CADD-splice scores?

### ISSUE THREAD

**Issue by zyh4482** [kircherlab/CADD-scripts#38]
I found CADD-splice has been implemented in CADD v1.6. 
I downloaded prescored annotated SNV and indel. 

I have some new indels and SNVs for splicing test. 

I tried to get scores from webserver. But there are only Rawscore and PHRED in output. 

I'm now using standalone script. But there are few documents mentioned how to get CADD-splice score. 

May I ask how to get these scores? Thanks

**Comment by makirc** [comment]
Hi there! Yes, CADD v1.6 incorporates MMSplice and SpliceAI scores in its score calculation. Please consult with the respective MMSplice and SpliceAI implementations for which positions they are defined. They are not defined genome-wide, but just within a certain basepair context of a transcript. You can see the annotations that CADD incorporates (as well as some additional ones that are just reported as annotation for our users, see long table in https://cadd.bihealth.org/static/ReleaseNotes_CADD_v1.6.pdf for details) when you check "include annotations" on the scoring website. Similarly, you have to specifically request annotations in the offline scoring scripts. Best, Martin
