### ISSUE TITLE
Where is unzip CADD.zip?

### ISSUE THREAD

**Issue by feltus** [kircherlab/CADD-scripts#41]
Hi.  I am trying to install CADD on our cluster.  Where is CADD.zip?  Is it this file:  https://krishna.gs.washington.edu/download/CADD/v1.6/GRCh38/annotationsGRCh38_v1.6.tar.gz

**Comment by aerval** [comment]
Hey, `CADD.zip` refers to the release of the scripts, i.e the entirety of this github repository. The most recent version of this is https://github.com/kircherlab/CADD-scripts/archive/refs/tags/v1.6.post1.zip (The name unfortunately changes with each release)
