### ISSUE TITLE
Which  prescored files are necessary?

### ISSUE THREAD

**Issue by JiahuaQu** [kircherlab/CADD-scripts#43]
Hi, from the manual installation guide, I went to the web page, https://cadd.bihealth.org/download, but found there are many different files for the same genome version. I want to use Genome build GRCh38 / hg38. Although their file names are kind of informative, there's no descriptive document to describe their difference. Their name likely indicated that some files are redundant to some degree and some files are too large, so should we download all files to run the program fast? Thank you.

**Comment by aerval** [comment]
Hello, no prescored files are necessary. They only exist to make scoring faster (and enable secondary analyses that i.e study all protein coding SNVs). Aside from that, the description is what those files are, i.e all SNVs are pretty much all possible SNVs in the genome, the Indels are previously observed InDels, gnomad contains previously observed SNVs. Annotation indicates if you will just get the CADD score or also the CADD annotations (depends on whether you run CADD with `-a` flag). You can have a look at all`tsv.gz` files content with `curl -s $FILE| zcat  |less`. Which files are necessary ultimately depends on your use case and what kind of variants you want to score. I.e if you just study frequent variants, you'd get the gnomAD files, else you should probably use all SNVs.

**Comment by JiahuaQu** [comment]
> Hello, no prescored files are necessary. They only exist to make scoring faster (and enable secondary analyses that i.e study all protein coding SNVs). Aside from that, the description is what those files are, i.e all SNVs are pretty much all possible SNVs in the genome, the Indels are previously observed InDels, gnomad contains previously observed SNVs. Annotation indicates if you will just get the CADD score or also the CADD annotations (depends on whether you run CADD with `-a` flag). You can have a look at all`tsv.gz` files content with `curl -s $FILE| zcat |less`. Which files are necessary ultimately depends on your use case and what kind of variants you want to score. I.e if you just study frequent variants, you'd get the gnomAD files, else you should probably use all SNVs.

Thank you very much for the immediate answer.
I'm still confused. Let me specify my questions further:
1. There are different files on whe web page:
(1) All possible SNVs of GRCh38/hg38
(2) All possible SNVs of GRCh38/hg38 incl. all annotations
(3) All gnomad release 3.0 InDels to initiate a local setup
(4) All gnomad release 3.0 InDels incl. all annotations to initiate a local setup
(5) All gnomad release 3.0 SNVs
(6) MD5Sums
(7) All GRCh38 annotations required for offline installation
2. Does (1) contain (5)?
3. As (5) does not have the corresponding incl. all annotations file, like (2) or (4), how to get its annotation in the result?
4. As other variants have already had annotation file, such as (2) and (4), what's the role of (7)?
5. Does (6) include multiple md5 for each other file?
6. I want to run the program fast on all kinds of variants and also get their annotations. Which files shoul I download? What did you mean by "all SNVs"? Did you mean all the seven files? Include InDel variants?
7. If I don't download any file but run the script (./CADD.sh -a -g GRCh38 -o outpu.tsv.gz test/input.vcf) directly, what kinds of results will be generated? Can the program automatically analyze all kinds of variants that are available for CADD?
8. Without downloading the files manually, how to specify the variant kinds for the program to anlaysis? For example, only analyze SNV or Indel?
I know these are alot of questions, but hope get your help.

**Comment by aerval** [comment]
Hello, no problem, that is what we are here for.

2. Yes,
3. You would need to use a VCF file and generate again (or subset from the all SNV file)
4. That is the repository of just the annotation files which are in a different format. This file is required to run `CADD.sh`. You would also need it to i.e annotate InDels that have not been prescored.
5. no, there is just one md5sum for each file (you can check the file, its just text and quite small)
6. you would want the all SNV file (with or without annotations) plus the gnomad Indel file.
7. You should get the same result like with the prescored files (with annotation, the order for variants with multiple consequences will change randomly due to VEP doing that). Yes, the program can and will analyze all kind of variants (exept INDEL longer than 50bp and variants outside of defined chromosome regions)
8. The vcf file contains the input to the script. In that file you specify the variants that you want to score.

I hope that clarifies a few of your issues.

Cheers, Philipp

**Comment by JiahuaQu** [comment]
Thank you.
Just to confirm: I need the files (2) and (4) and verified them with md5. Do I also need download file (7)? 
If I download the files, should I download all files or can I only download parts of files and leave other files to be retrieved by the program automatically when it runs?

**Comment by aerval** [comment]
Yes, you need file 7, plus files 2 and 4 if you want to run it faster, but you can also run it without those. Yes, it integrates those scores, that is the whole point of providing them together. (and to be honest, that is pretty much what the install.sh script does, just with a prompt).
