### ISSUE TITLE
incorrect url for PRESCORE_GRCh38_INDEL ?

### ISSUE THREAD

**Issue by wresch** [kircherlab/CADD-scripts#5]
Hi - 

the URL for the GRCh38 prescored InDels in the installer script seems to be wrong

https://github.com/kircherlab/CADD-scripts/blob/232fc0bda9f9ed127694f1d38669db043918328e/install.sh#L104

`InDels_SNVs.tsv.gz` does not exist. `InDels.tsv.gz` does and that is incidentally also the name of the file for GRCh37.

**Comment by aerval** [comment]
Weird, thanks a lot for reporting.
