### ISSUE TITLE
annotation error

### ISSUE THREAD

**Issue by Mong-yj** [kircherlab/CADD-scripts#50]
Hi,

I executed the command "./CADD.sh test/input.vcf" and got the following error.

"""
Activating conda environment: envs/56b93169d3e29fd592952535267703b3_
[E::hts_hopen] Failed to open file /home/user/CADD-scripts-1.6.post1/data/annotations/GRCh38_v1.6//phastCons/hg38.phastCons.bg.gz
[E::hts_open_format] Failed to open file "/home/user/CADD-scripts-1.6.post1/data/annotations/GRCh38_v1.6//phastCons/hg38.phastCons.bg.gz" : Exec format error
Traceback (most recent call last):
  File "/home/user/CADD-scripts-1.6.post1/src/scripts/annotateVEPvcf.py", line 94, in <module>
    annotation.load(args)
  File "/home/user/script/CADD-scripts-1.6.post1/src/scripts/lib/Annotations.py", line 30, in load
    self.tabix = pysam.TabixFile(self.path,'r'),None,None,None,None,None,None,"%s annotation" % self.name
  File "pysam/libctabix.pyx", line 350, in pysam.libctabix.TabixFile.__cinit__
  File "pysam/libctabix.pyx", line 391, in pysam.libctabix.TabixFile._open
IOError: could not open file `/home/user/CADD-scripts-1.6.post1/data/annotations/GRCh38_v1.6//phastCons/hg38.phastCons.bg.gz`
"""

The same error for another file occurred when the command "./CADD.sh -a -g GRCh37 -o output_inclAnno_GRCh37.tsv.gz test/input.vcf" of version GRCh37.

"""
IOError: could not open file `/home/user/CADD-scripts-1.6.post1/data/annotations/GRCh37_v1.6//mutation_density/mutDensity_gnomAD/variant_density.gnomad.2.0.1.100.bg.gz`
"""

If I open the file in that location directly, it will open normally.
What's the problem?

Thank you.

**Comment by visze** [comment]
Please reopen if it is still relevant.
