### ISSUE TITLE
gnomAD AF annotations

### ISSUE THREAD

**Issue by HagenC** [kircherlab/CADD-scripts#6]
Hi,

Is it possible to add gnomAD AF annotations for GRCh38 using offline setup?

Cheers,
Hagen

**Comment by aerval** [comment]
Hey,

I have added this as a [feature branch](https://github.com/kircherlab/CADD-scripts/tree/f-gnomAD_AF) but won't add it to the main release. The reason we removed this was that multiple publications cite CADD as using allele frequency which it doesn't.

Note that you will have to download the gnomad variant file (plus .tbi) under the path /data/GRCh37/gnomad. I used gnomad 2.1 here. Also note that this obviously does not work with our prescored files.

If you need more features from gnomAD, parse them like I did in Annotations.py :
- add them in the feature list of the object
- parse the value to the res dictionary
- for annotation free scores adjust column numbers in CADD.sh

Cheers, Philipp
