### ISSUE TITLE
how to get CADD for variants on chrX 

### ISSUE THREAD

**Issue by zhangpicb** [kircherlab/CADD-scripts#62]
Dear @holtgrewe @EvanTheB @makirc @visze @aerval 

Thanks for the great tools!

I use the https://cadd.gs.washington.edu/score to get CADD score

```
chr1    752566  .       G       A       . 
chrX    119589419       .       ACA     A       . 
chrX    119602961       .       G       T       .
```

BUT variants on chrX have no CADD score.

```
##CADD GRCh37-v1.7 (c) University of Washington, Hudson-Alpha Institute for Biotechnology and Berlin Institute of Health at Charite - Universitaetsmedizin Berlin 2013-2023. All rights reserved.
#Chrom	Pos	Ref	Alt	RawScore	PHRED
1	752566	G	A	-0.192970	0.723
```

How to get CADD scores for variants on chrX ?

Thanks in advanced!

**Comment by visze** [comment]
Hi

I looked up your last SNV and it seems that the reference on GRCh37 is C not G

Here is a direct link to the SNV lookup: https://cadd.gs.washington.edu/snv/GRCh37-v1.7/X:119602961_C_T

When there are errors in the lookup/score generation the variant will not show up in the final results.

Please make sure that your VCF file is formatted correctly and you have the correct reference allele.

**Comment by zhangpicb** [comment]
Hi @visze 

Thanks for your quick reply!

You are right!

Thanks again!
