### ISSUE TITLE
ESM-1v in CADD

### ISSUE THREAD

**Issue by jerome-f** [kircherlab/CADD-scripts#74]
Hi,

I was looking through the annotations file and noticed that the ESM-1v scores for indel/frameshift variants are always on the extremes by an order of magnitude compared to snv missense variants. This I am assuming comes from summing the LLR of the scores. Does this bias the final CADD scores in anyway? To always score coding indels and frameshift s in the top 1 percentile? I know it is one component of the 153 that go into score calibration but wanted to check if this had been looked at. I'd also recommend the pseudo LLR formulation from ESM-1b if a bias does exist.

**Comment by ThorbenMaa** [comment]
Hi Jerome,
you are right with your assumption that the relatively high scores for InDels and frameshifts result from summing up over many residues. However, ESM1-v for InDels, frameshifts, and missense variants are each treated as an individual feature. As each feature is standardized and has its own coefficient in the logistic regression approach, there shouldn't be any bias in the resulting CADD scores. I agree that we could have made this point more clear in our manuscript.

Hope this helps,
Thorben!

**Comment by jerome-f** [comment]
Thanks Thorben. It does and that's makes sense.
