### ISSUE TITLE
Fix CreateCondaEnvironmentException error

### ISSUE THREAD

**Issue by johnbradley** [kircherlab/CADD-scripts#75]
When running with the latest snakemake the following error occurs:
```
CreateCondaEnvironmentException:
Conda must be version 24.7.1 or later, found version 24.3.0. Please update conda to the latest version. Note that you can also install conda into the snakemake environment without modifying your main conda installation.
```
[Snakemake now requires conda >24.7.1](https://github.com/snakemake/snakemake/blob/main/CHANGELOG.md#8206-2024-10-07).

**Comment by johnbradley** [comment]
The error seems to be due to the version of conda in this container: visze/cadd-scripts-v1_7:0.1.0.
Perhaps just rebuilding the container would fix this issue.

**Comment by visze** [comment]
Thank you for letting us know..yes you are right. I have to rebuild the
container. I might do a new script release too to improve a bit the
performance and get rid of the default channel (anaconda license issue).

John Bradley ***@***.***> schrieb am Do., 7. Nov. 2024, 16:57:
