### ISSUE TITLE
Different result for the same dataset

### ISSUE THREAD

**Issue by fish2022Jul** [kircherlab/CADD-scripts#77]
Hi , I installed CADD v1.7.2 on my linux system with conda 24.9.2 and snakemake 8.25.3. when I run 
CADD.sh -m -p -a -d  test/input.vcf.gz
under /data/apps/CADD/1.7.2/CADD-scripts-1.7.2. it works well. and log shows "localrule annotation_vep" ran after "localcheckpoint prescore". 
But when I copy input.vcf.gz to another place and run the same command, I got this error:
```
MissingInputException in rule annotate_esm in file /data/apps/CADD/1.7.2/CADD-scripts-1.7.2/Snakefile, line 131:
Missing input files for rule annotate_esm:
    output: /lscratch/41104573/tmp.EQiCgGxenj/input.esm_missens.vcf.gz, /lscratch/41104573/tmp.EQiCgGxenj/input.esm_frameshift.vcf.gz, /lscratch/41104573/tmp.EQiCgGxenj/input.esm.vcf.gz
    wildcards: file=/lscratch/41104573/tmp.EQiCgGxenj/input
    affected files:
        data/annotations/GRCh38_v1.7/esm/pep.110.fa
        data/annotations/GRCh38_v1.7/esm/esm1v_t33_650M_UR90S_4.pt
        data/annotations/GRCh38_v1.7/esm/esm1v_t33_650M_UR90S_1.pt
        data/annotations/GRCh38_v1.7/esm/esm1v_t33_650M_UR90S_3.pt
        data/annotations/GRCh38_v1.7/esm/esm1v_t33_650M_UR90S_2.pt
        data/annotations/GRCh38_v1.7/esm/esm1v_t33_650M_UR90S_5.pt
```
The log show "rule annotate_esm" ran after "localcheckpoint prescore", which skipped "localrule annotation_vep". I found input.novel.vcf under /lscratch/41104573/tmp.EQiCgGxenj. but no further analysis.

I did set CADD env parameter by check "echo $CADD" I got "/data/apps/CADD/1.7.2". 
It seems when I leave /data/apps/CADD/1.7.2/CADD-scripts-1.7.2, CADD.sh can't find dataset although I have files under /data/apps/CADD/1.7.2/data/annotations/GRCh38_v1.7/esm/pep.110.fa. Any suggestions? Thank you

**Comment by visze** [comment]
Can you give me yout comple code you run CADD?

CADD.sh have to be in the scripts folder. It always will use the environment path `$CADD` from the location of `CADD.sh`

It is important that annotations have to be in the `$CADD/data/annotations/` (and the prescored also).

This can be very very tricky when using apptainer for the conda environments. Here you have to use additional bindings of folders

**Comment by visze** [comment]
Oh seems to be similar to #78
