### ISSUE TITLE
Ambiguous Wording for Annotation Downloads

### ISSUE THREAD

**Issue by DarioS** [kircherlab/CADD-scripts#9]
I read the README file, but it's unclear from the description if prescored files are a superset of the information in the basic files or whether they contain distinct information. In other words, do I download either "All possible SNVs of GRCh38/hg38 (80 GB)" or "All possible SNVs of GRCh38/hg38 incl. all annotations (292 GB)" (and similarly for indels) or is it necessary to download both kinds of files?

**Comment by aerval** [comment]
Hello Dario,
The smaller file is indeed a subset of the larger one and only contains the general variant information (i.e Chromosome, Position, Reference and Alternative) plus the CADD score (Raw and Phred Score)
and would be generated similar to this:
```bash
zcat whole_genome_SNVs_inclAnno.tsv.gz | cut -f 1-4,124,125 | uniq | bgzip -c > whole_genome_SNVs.tsv.gz
```
Note: As we annotate multiple consequences to some variants (e.g if it is found as missense in one transcript and in the 3' UTR of another) the line numbers between the two files are not the same, however different consequences annotated to one variant have the same CADD score (i.e the `uniq` call in the one-liner above).

You can check the list of annotations for an example here:
without annotation: https://cadd.gs.washington.edu/snv/GRCh38-v1.5/21:43451447
with annotation: https://cadd.gs.washington.edu/snv/GRCh38-v1.5_inclAnno/21:43451447
which is generated via a tabix call on the two files.
(the variant files have all information per variant in the usual CADD tsv format).

Cheers, Philipp

**Comment by DarioS** [comment]
I will use the smaller file then.
